### ISSUE TITLE
Shortcuts not working on Mac

### ISSUE THREAD

**Issue by georgeherby** [cheluskis/hangremote#12]
I have tried both the shortcuts but they are not working with the default. I tried other key bindings with no luck.

![image](https://user-images.githubusercontent.com/21989833/89399080-df583980-d709-11ea-93a5-f020b7880f50.png)

Chrome Version 84.0.4147.105 (Official Build) (64-bit)
macOS Catalina 10.15.6 (19G73)

**Comment by chelorossi** [comment]
They do work,

For more info go to:
[here](https://github.com/cheluskis/hangremote/issues/5)

Starring is more than welcome to support this non-profit project.

Best.
