### ISSUE TITLE
Camera Off not Working in Meet

### ISSUE THREAD

**Issue by fbetteo** [cheluskis/hangremote#3]
Hi.
I have installed the extension and used the "No Camera at start". It is working for hangouts calls just fine, but I tried it in a google meet link and the camera is On since I enter the room and after to the call.
Is this regular behaviour or something might be broken?
Thanks and congratz for the app!

**Comment by voglster** [comment]
I am seeing the same issue with meet.google.com when I start a business call.

**Comment by chelorossi** [comment]
Thanks for reporting.
I could already reproduce the issue, and I am addressing this issue anytime soon.
There is already a quickfix for the english version of meet (not available in chrome store, in here #2 ). Thanks to @bhank ( #2 )

Regards,

**Comment by bainonline** [comment]
Where can i download the quick fix build?

**Comment by chelorossi** [comment]
Should be updated in the next hour in the Chrome Store.
***Simply update manually or restart your browser.***
apologizes for the inconvenience, this is a non-profit self maintained extension, thanks for your support. 
Enjoy Google Meet support again!
Best

**Comment by voglster** [comment]
No problem man! Appreciate the fix and making the extension publically available on your spare time!
