### ISSUE TITLE
keyboard shortcut for mute?

### ISSUE THREAD

**Issue by cdbattags** [cheluskis/hangremote#5]
```
Or keyboard shortcuts (editable):

 - Ctrl+Shift+8 - Toggle Webcam
 - Ctrl+Shift+7 - Toggle Microphone

Please report any issue before rating if you have any, I will gladly help
```

How do I edit these or get this keyboard shortcut working on macOS?

**Comment by chelorossi** [comment]
Replace Ctrl key for CMD, that would be:

```
 - cmd+Shift+8 - Toggle Webcam
 - cmd+Shift+7 - Toggle Microphone
```
additionally you can customize it yourself going to this URL in chrome bar:

[chrome://extensions/shortcuts](chrome://extensions/shortcuts)

Please close this issue if this solves it.

happy hangouts!,
Kind Regards

**Comment by cdbattags** [comment]
Modifying the shortcuts doesn't seem to be working for me, hmmmm.

**Comment by cdbattags** [comment]
Seems to be the shortcuts in general for the extension aren't registering. I tested the `querySelector` and the check boxes for no mic and no camera work great!

If you have any ideas please let me know or else I think I'll fork and play with it myself this weekend.

**Comment by sfdc-slumos** [comment]
Global shortcut setting seems to do nothing for me. I'm currently using [Meet Mute](https://github.com/mattsimonis/meet-mute) (also on GitHub, if somebody has bandwidth to compare them) for the global shortcuts and Hangremote for the "at start" settings. 😂

**Comment by chelorossi** [comment]
Hey folks,

You must have that key combination in use. To troubleshoot this you can do (as extension web store images hints):


1. enter chrome://extensions/shortcuts (on chrome bar)
2. you will see:
 ![image](https://user-images.githubusercontent.com/408969/78930250-2bf07880-7a7a-11ea-8d2a-65459ee76f6b.png)
4. provide your key shortcuts
5. **restart chrome** (please make you sure you fully quit, e.g. right click-quit on icon)

If it does not work, try again disabling all other extensions.

Please let me know your feedback!,
apologizes for the inconvenience, this is a non-profit self maintained extension, thanks for your support.
Also rate 5 stars.

**Comment by chelorossi** [comment]
@cdbattags @sfdc-slumos have you been able to check?
thanks,

**Comment by chelorossi** [comment]
Closed,
Starring is more than welcome to support the project.
