### ISSUE TITLE
Add option to auto-enter in a Meet room

### ISSUE THREAD

**Issue by aslafy-z** [cheluskis/hangremote#9]
Thanks for this awesome extension!

I'd love to see an option that auto-enter into Google Meet meetings when I open the URL. I'd save me for a click, and would work so good with the settings this extension provides.

**Comment by chelorossi** [comment]
Hey @aslafy-z ,

Thanks for the suggestion!.
Not having time for this now, you are more than welcome to suggest a PR.


Best
